brace_style = "SameLineWhere"
enum_discrim_align_threshold = 40
max_width = 140
struct_field_align_threshold = 40
struct_lit_single_line = true
unstable_features = true
use_field_init_shorthand = true
version = "Two"
where_single_line = true